- name: Run preflight checks
  ansible.builtin.import_tasks: preflight.yml

- name: Install RKE2 
  ansible.builtin.import_tasks: install.yml 

- name: Configure and start RKE2 server 
  ansible.builtin.import_tasks: server.yml
  when: rke2_role == "server"